version: 2
jobs:

  build:
    environment:
      GOFLAGS: -mod=vendor
    docker:
      - image: ncabatoff/dbms_exporter_builder:1.1.5
    steps:
      - checkout
      - run: make vet test dbms_exporter
      - persist_to_workspace:
          root: .
          paths:
            - dbms_exporter
            - sybase-short.yaml
            - postgres.yaml

  testpg:
    docker:
      - image: docker:stable-git
    steps:
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - run: docker run -d --name pg -e 'POSTGRES_PASSWORD=pgpass' postgres:11
      - run: |
          docker create -v /de --name de debian:stretch /bin/true
          docker cp workspace/. de:/de
      - run: >
          docker run --network container:pg -d
          --volumes-from de
          -e DATA_SOURCE_NAME='postgresql://postgres:pgpass@localhost:5432/?sslmode=disable'
          debian:stretch
          /de/dbms_exporter -queryfile /de/postgres.yaml -driver postgres
      - run: |
          test 0 -lt $(docker run --network container:pg byrnedo/alpine-curl --retry 10 --retry-connrefused localhost:9113/metrics |
            awk '/postgres_pg_stat_activity_count[{]datname="postgres",state="active"[}]/{ print $2 }')

  testsyb:
    docker:
      - image: docker:stable-git
    steps:
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - run: docker run -d --name syb -e 'SYBASE_USER=guest' -h dksybase datagrip/sybase:16.0
      - run: |
          docker create -v /de --name de debian:stretch /bin/true
          docker cp workspace/. de:/de
          sleep 60
      - run: >
          docker run --name sybde --network container:syb -d
          --volumes-from de
          -e DATA_SOURCE_NAME='compatibility_mode=sybase;user=guest;pwd=guest1234;server=localhost:5000'
          debian:stretch
          /de/dbms_exporter -queryfile /de/sybase-short.yaml -driver sybase -persistent.connection=true
      - run: |
          test 0 -lt $(docker run --network container:syb byrnedo/alpine-curl --retry 10 --retry-connrefused localhost:9113/metrics |
            awk '/sybase_spid_count_by_user_conns[{]dbuser="guest"[}]/{ print $2 }')

  image:
    environment:
        IMAGE_NAME: ncabatoff/dbms_exporter
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .
      - run: |
          echo "$DOCKERHUB_PASSWORD"| docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME:latest

  release:
    environment:
      GOFLAGS: -mod=vendor
    docker:
      - image: ncabatoff/dbms_exporter_builder:1.1.5
    steps:
      - checkout
      - run: curl -LO https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_amd64.deb
      - run: dpkg -i goreleaser_amd64.deb
      - run: goreleaser release

  release_image:
    environment:
      IMAGE_NAME: ncabatoff/dbms_exporter
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          IMAGE_TAG=${CIRCLE_TAG/v/''}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "$DOCKERHUB_PASSWORD"| docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build_and_image:
    jobs:
      - build
      - testpg:
          requires:
            - build
      - testsyb:
          requires:
            - build
      - image:
          requires:
            - testpg
            - testsyb
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release_image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
