version: 2
jobs:

  build:
    environment:
      GOFLAGS: -mod=vendor
    docker:
      - image: ncabatoff/dbms_exporter_builder:1.1.5
    steps:
      - checkout
      - run: make vet test dbms_exporter

  image:
    environment:
        IMAGE_NAME: ncabatoff/dbms_exporter
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .
      - run: |
          echo "$DOCKERHUB_PASSWORD"| docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME:latest

  release:
    environment:
      GOFLAGS: -mod=vendor
    docker:
      - image: ncabatoff/dbms_exporter_builder:1.1.5
    steps:
      - checkout
#      - run: sudo apt-get -qq update
#      - run: sudo apt-get install -y rpm
      - run: curl -sL https://git.io/goreleaser | bash

  release_image:
    environment:
      IMAGE_NAME: ncabatoff/dbms_exporter
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          IMAGE_TAG=${CIRCLE_TAG/v/''}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "$DOCKERHUB_PASSWORD"| docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build_and_image:
    jobs:
      - build
      - image
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release_image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
