name: PR Validator
run-name: Validating PR on ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened


jobs:
  pr-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: croesusfin/pr-validator@v1
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          # Has predefined ./commitlintrc.js if not specified